create header and filter
lucasmassei/namovies pull request #1
Opened 2021-05-18 11:35 UTC by lucasmassei

2021-05-18 13:13 UTC, gqueiroz1 requested changes

2021-05-18 13:13 UTC, gqueiroz1 commented on public/css/style.css
> +}
tem q corrigir aqui, alem de mto especifico esta estatico, vc pode usar proporção e cuidar no responsivo

```
.container {
  width: 67.7%;
  margin: 0 auto;
}
```

67.7% => 130/1920 (proporção para full hd)
No responsivo obviamente vc vai precisar aumentar isso, se não vai ficar pequeno demais.. geralmente 90% - 95% já tá bom

2021-05-18 13:13 UTC, gqueiroz1 commented on public/css/style.css
> +}
Aqui eu acho melhor criar uma classe separada pra cada coisa.
Se não você vai ter uma classe `font-arial-bold`, `font-arial-normal`, vc pode usar só `arial` e depois mudar de acordo com a classe `bold` ou `normal`

2021-05-18 13:13 UTC, gqueiroz1 commented on public/css/style.css
> +}
O mesmo pra roboto

2021-05-18 13:13 UTC, gqueiroz1 commented on src/App.vue
>  </style>
sem uso, remover

2021-05-18 13:13 UTC, gqueiroz1 commented on src/App.vue
> +</script>
sem uso, remover

2021-05-18 13:13 UTC, gqueiroz1 commented on public/css/reset.css
> +* {
adiciona *::after e *::before

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Filter.vue
> +    <div class="position-relative flex">
substitui essa div por um `form`, adiciona um `@submit` pra pegar o evento de submissão da pesquisa pelo botão.

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Filter.vue
> +      <button class="nm-filter__icon position-absolute secondary-color">
adiciona um `type="submit"`, pra ele poder enviar o `@submit` lá pro form

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Filter.vue
> +        <div v-if="showMenu === 'gender'" class="nm-menudrop position-absolute">
Vamos colocar no padrão da nave.
Pra não usar essa lógica na view, e manter um código pequeno lá no script, podemos usar um método.

```
checkSelectedDropdownMenu (menu) {
  return this.showMenu === menu
}
```

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Filter.vue
> +        <div v-if="showMenu === 'gender'" class="nm-menudrop position-absolute">
Eu havia colocado `openSpecificDropdownMenu` no nome do método.. mas o que a gente tá fazendo aqui é uma responsabilidade de checagem.
Ele vai verificar se `this.showMenu` é igual ao `menu` passado praquele caso, se for, ele abre. Isso só vai acontecer quando clicar na div que tem o `@click="openDropdownMenu"`.

Então a responsabilidade de abertura (troca de valor da variável) é do `openDropdownMenu`, não fez muito sentido pra mim manter aquele nome, um `check` fica melhor.

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Filter.vue
> +      </div>
Depois que corrigir a lógica q eu falei ali em cima, vamos melhorar esse código reduzindo todo esse código do template.

Podemos usar o javascript pra fazer o template, passando para as diretivas, props e etc todos os dados que precisamos em formato de objeto.

Só pra você entender, vou colocar o código aqui mas quando for fazer essa parte me chama pra fazer com você.

Template:
```
<div v-for="(item, index) in filterOptions" class="nm-filter__items secondary-color position-relative">
  <div class="flex" @click="openDropdownMenu(item.type)">
    <li class="nm-filter__keydrop">{{ item.label }}</li>
    <i class="nm-filter__drop fas fa-chevron-down"></i>
  </div>
  <div v-if="checkSelectedDropdownMenu(item.type)" class="nm-menudrop position-absolute">
    <ul class="font-arial-bold primary-color">
      <li class="nm-menudrop__item" v-for="option in item.options" @click="filter(option.value)">{{ option.label }}</li>
    </ul>
  </div>
</div>
```

Script:
```
computed: {
  filterOptions () {
    return [
      {
        type: 'gender',
        label: 'Gênero',
        options: [
          {label: 'Ação', value: 'action'},
          {label: 'Fantasia', value: 'fantasy'}
        ]
      },
      {
        type: 'rate',
        label: 'Nota mínima',
        options: [
          {label: '1', value: 1},
          {label: '2', value: 2}
        ]
      } 
    ]
  }
}
```

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Filter.vue
> +.nm-filter__icon {
Você pode usar `flexbox` pra fazer esse tipo de alinhamento. Sempre que puder evitar o uso de positions, evite. Menos dor de cabeça no responsivo e caso precise de alteração

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Header.vue
> +      <li class="nm-header__link"><router-link class="primary-color" :to="{name: 'Favorites'}">Meus favoritos</router-link></li>
O mesmo que vamos fazer para o filtro, podemos fazer aqui

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Header.vue
> +  margin-bottom: 68px;
mto específico, n?

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Header.vue
> +  margin-right: 13px;
mto específico, geralmente layout é número cheio, 10, 15...

2021-05-18 13:13 UTC, gqueiroz1 commented on src/components/Header.vue
> +  margin-right: 13px;
Se algum 13 apareceu la no layout, provavelmente é pq n pegou o espaçamento correto, vc pode arredondar pra 15

2021-05-19 12:00 UTC, caiotarifa requested changes

2021-05-19 12:00 UTC, caiotarifa commented on src/components/Filter.vue
> +      }
``` js
this.showMenu = this.showMenu === menu ? false : menu
```

2021-05-19 12:00 UTC, caiotarifa commented on src/components/Filter.vue
> +    openDropdownMenu (menu) {
Se há o valor `false`, então além de `open` pode haver o `close`. Nesse caso, melhor trocar `openDropdownMenu` por `toggleDropdownMenu`.

2021-05-19 12:00 UTC, caiotarifa commented on src/components/Header.vue
> +    <h1 class="nm-header__title align-self-center font-arial-bold primary-color">NaMovies</h1>
Identação está errada.

2021-05-19 13:46 UTC, gqueiroz1 approved these changes

2021-05-19 13:46 UTC, merged